on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: quannghia/msp430-gcc-new:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - run: make format
      - run: make cppcheck
      - run: TOOLS_PATH=/home/ubuntu/dev/tools make